# Generated by Django 5.2 on 2025-06-27 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ems_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alarm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parameter", models.CharField(max_length=20)),
                ("level", models.CharField(max_length=20)),
                ("value", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("notified_to", models.EmailField(max_length=254)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ems_app.machine",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Threshold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parameter",
                    models.CharField(
                        choices=[
                            ("kWh", "Energy (kWh)"),
                            ("current", "Current (A)"),
                            ("voltage", "Voltage (V)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "threshold_value",
                    models.FloatField(help_text="Full-scale value (e.g. 500 kWh)"),
                ),
                (
                    "percentage",
                    models.FloatField(
                        help_text="Trigger alarm when this % of value is exceeded"
                    ),
                ),
                ("level", models.CharField(max_length=20)),
                ("contact_email", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thresholds",
                        to="ems_app.machine",
                    ),
                ),
            ],
        ),
    ]
