# Generated by Django 5.2 on 2025-06-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ems_app", "0002_alarm_threshold"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tariff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="machine",
            name="current_tag",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="machine",
            name="kwh_tag",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="machine",
            name="voltage_tag",
            field=models.IntegerField(),
        ),
    ]
