# Generated by Django 5.2 on 2025-06-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ems_app", "0003_tariff_alter_machine_current_tag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tariff",
            name="emission_factor",
            field=models.FloatField(default=0.82, help_text="kg CO₂ per kWh"),
        ),
    ]
